language: node_js
node_js:
- '6'
install:
- npm install
after_success: npm run coveralls
deploy:
  provider: npm
  email: m@eridem.net
  api_key:
    secure: Gre71y9FfMCE0++gph5DNXaH3POtTnRAm8mhCvYC/AmstBswRP7Xd0ZgFIvKYg4omLHTfdKJbwZyWVd8AVVVLpaBdMXkNpRlZPtJuXk4hYzcnlEHXoFWQKX094e+NGfmlrRTatBe7WphRfDr/7KcOMW5otCUi6qPDCzKJcarahD6sxuhGXAXWY1LsBG7+UdyqJctRNcV8018ZXkOsnRLTihey1XmuzfzgY1Uu86RacXc+Y45eMrbXdPaSjTgYfNxLBng1mxzRm1pGRqk4ZkYKXxHVlrhSMuPPfK2jQiHUaXR9PeIPM/lyn3GVpecL3aVoLoUAhR+BzV2fyymIMV/3lH6ngxcFHycXisGxe6HszPLa0Pjj489FYLuZCSHtrKVBfrpzSaaWJ0JUCdQ5mcWFs7LVookAqFhprUjzgmX2FdwiZ5JPg6G1CBsKGyr/e/64CJdiqAON1xjkqeov8Vz1yOqQEO+hItOmVDEvqXUw/dVgIn+EgkagkdRlA+u1R1GinPhejJAt3A8RqY111LQgo08ovaX63jQp43UOFhTsEqebkPwcvL+0VxReLe6plfIb2B8AZqcGksS1iHTO5gBVwecfWwWMc2VMz5Hf6JeC38NmQXwzuCgJ4c44AaAb30dcryWiixMbyo0z+LeY1sudjGY9RqbYxZYJHv/6mdEVPQ=
  on:
    tags: true
    repo: eridem/hostify
